import { Question } from './types';

export const QUESTIONS: Question[] = [
  {
    key: 'bunri',
    step: 'bunri',
    title: '文理',
    subtitle: '文系または理系を選択してください。',
    options: ['文系', '理系'],
  },
  {
    key: 'graduation_year',
    step: 'graduation_year',
    title: '卒業見込み年度',
    subtitle: '卒業見込み年度を選択してください。',
    options: ['2026年', '2027年', '2028年', '2029年'],
  },
  {
    key: 'name',
    step: 'name',
    title: '氏名',
    subtitle: '例：山田 太郎',
    options: [],
  },
  {
    key: 'university',
    step: 'university',
    title: '大学名',
    subtitle: '例：〇〇大学',
    options: [],
  },
  {
    key: 'faculty',
    step: 'faculty',
    title: '学部',
    subtitle: '例：経済学部',
    options: [],
  },
  {
    key: 'industry_interests',
    step: 'industry_interests',
    title: '興味のある業種・業界',
    subtitle: '複数選択可（最大5つ）。カンマ区切りで入力してください。',
    options: [
      '商社',
      'IT・通信',
      'コンサルティング',
      'メーカー',
      '金融（証券・銀行・保険など）',
      '人材サービス・BPOサービス',
      'インフラ（エネルギー・交通）',
      '広告・出版・マスコミ',
      '官公庁・教育',
      'その他',
    ],
    multiple: true,
    maxSelections: 5,
  },
  {
    key: 'career_interests',
    step: 'career_interests',
    title: 'キャリアの関心',
    subtitle: '複数選択可（最大5つ）。カンマ区切りで入力してください。',
    options: [
      '自分のスキルや経験を活かせる',
      '会社の理念やカルチャーに共感できる',
      '若いうちから裁量権が多い',
      'グローバルで働くチャンスがある',
      '社会課題解決に取り組みたい',
      '福利厚生が充実している',
      '年収や環境が安定している',
      '研修／教育制度が充実している',
      '社内の人の雰囲気が自分と合っている',
      'リーダーシップを発揮できる',
      '特定の分野で専門性を磨く',
    ],
    multiple: true,
    maxSelections: 5,
  },
  {
    key: 'preferred_location',
    step: 'preferred_location',
    title: '希望勤務地',
    subtitle: '希望勤務地を選択してください。',
    options: ['北海道/東北', '関東', '中部', '近畿', '中国/四国', '九州', 'どこでも/選ばない'],
  },
  {
    key: 'company_size',
    step: 'company_size',
    title: '会社規模',
    subtitle: '会社規模を選択してください。',
    options: [
      '大手企業（目安：2,000人〜）',
      'メガベンチャー（目安：1,000人〜1,999人）',
      '中小企業・中堅企業（目安：100人〜999人）',
      'ベンチャー（目安：30人〜99人）',
      'スタートアップ（目安：1人〜29人）',
      'まだ決まっていない',
    ],
  },
  {
    key: 'college_experience',
    step: 'college_experience',
    title: '大学時代に経験したこと',
    subtitle: '複数選択可。カンマ区切りで入力してください。',
    options: [
      '長期インターン（2ヶ月以上）',
      '短期留学（〜3ヶ月）',
      '長期留学（4ヶ月〜）',
      'ボランティア',
      '学生団体',
      '部活動',
      'チームリーダー（5名以上）',
      '学生起業（法人登記有り）',
      '学生起業（法人登記なし）',
      '特になし',
    ],
    multiple: true,
  },
  {
    key: 'qualifications',
    step: 'qualifications',
    title: '資格',
    subtitle: '複数選択可。カンマ区切りで入力してください。',
    options: [
      'TOEIC L&R（600〜725点）',
      'TOEIC L&R（730〜795点）',
      'TOEIC L&R（800点以上）',
      '英検 準1級以上',
      '日商簿記 2級以上',
      'FP（ファイナンシャル・プランニング技能士）2級以上',
      'ITパスポート',
      '基本情報技術者 / 応用情報技術者',
      'G検定 / DX検定',
      '宅地建物取引士',
      'MOS',
      'その他',
    ],
    multiple: true,
  },
  {
    key: 'pr',
    step: 'pr',
    title: 'PR（任意）',
    subtitle: '自己PRや補足事項があれば入力してください。',
    options: [],
  },
];

